//TEST
export const ADD_NEW_TEST_REQUESTING = "App/ADD_NEW_TEST_REQUESTING"
export const ADD_NEW_TEST_SAGA_REQUESTING = "App/ADD_NEW_TEST_SAGA_REQUESTING"
export const ADD_NEW_TEST_SUCCESS = "App/ADD_NEW_TEST_SUCCESS"
export const ADD_NEW_TEST_ERROR = "App/ADD_NEW_TEST_ERROR"

export const GET_TEST_REQUESTING = "App/GET_TEST_REQUESTING"
export const GET_TEST_SAGA_REQUESTING = "App/GET_TEST_SAGA_REQUESTING"
export const GET_TEST_SUCCESS = "App/GET_TEST_SUCCESS"
export const GET_TEST_ERROR = "App/GET_TEST_ERROR"

//PARAMETER
export const ADD_NEW_PARAMETER_REQUESTING = "App/ADD_NEW_PARAMETER_REQUESTING"
export const ADD_NEW_PARAMETER_SAGA_REQUESTING = "App/ADD_NEW_PARAMETER_SAGA_REQUESTING"
export const ADD_NEW_PARAMETER_SUCCESS = "App/ADD_NEW_PARAMETER_SUCCESS"
export const ADD_NEW_PARAMETER_ERROR = "App/ADD_NEW_PARAMETER_ERROR"

export const GET_PARAMETER_REQUESTING = "App/GET_PARAMETER_REQUESTING"
export const GET_PARAMETER_SAGA_REQUESTING = "App/GET_PARAMETER_SAGA_REQUESTING"
export const GET_PARAMETER_SUCCESS = "App/GET_PARAMETER_SUCCESS"
export const GET_PARAMETER_ERROR = "App/GET_PARAMETER_ERROR"

//UNIT
export const ADD_NEW_UNIT_REQUESTING = "App/ADD_NEW_UNIT_REQUESTING"
export const ADD_NEW_UNIT_SAGA_REQUESTING = "App/ADD_NEW_UNIT_SAGA_REQUESTING"
export const ADD_NEW_UNIT_SUCCESS = "App/ADD_NEW_UNIT_SUCCESS"
export const ADD_NEW_UNIT_ERROR = "App/ADD_NEW_UNIT_ERROR"

export const GET_UNIT_REQUESTING = "App/GET_UNIT_REQUESTING"
export const GET_UNIT_SAGA_REQUESTING = "App/GET_UNIT_SAGA_REQUESTING"
export const GET_UNIT_SUCCESS = "App/GET_UNIT_SUCCESS"
export const GET_UNIT_ERROR = "App/GET_UNIT_ERROR"

//RECORD
export const ADD_NEW_RECORD_REQUESTING = "App/ADD_NEW_RECORD_REQUESTING"
export const ADD_NEW_RECORD_SAGA_REQUESTING = "App/ADD_NEW_RECORD_SAGA_REQUESTING"
export const ADD_NEW_RECORD_SUCCESS = "App/ADD_NEW_RECORD_SUCCESS"
export const ADD_NEW_RECORD_ERROR = "App/ADD_NEW_RECORD_ERROR"

export const GET_RECORD_REQUESTING = "App/GET_RECORD_REQUESTING"
export const GET_RECORD_SAGA_REQUESTING = "App/GET_RECORD_SAGA_REQUESTING"
export const GET_RECORD_SUCCESS = "App/GET_RECORD_SUCCESS"
export const GET_RECORD_ERROR = "App/GET_RECORD_ERROR"


export const DELETE_RECORD_REQUESTING = "App/DELETE_RECORD_REQUESTING"
export const DELETE_RECORD_SAGA_REQUESTING = "App/DELETE_RECORD_SAGA_REQUESTING"
export const DELETE_RECORD_SUCCESS = "App/DELETE_RECORD_SUCCESS"
export const DELETE_RECORD_ERROR = "App/DELETE_RECORD_ERROR"